name: Build FilzaJailedDS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Theos
        uses: Randomblock1/theos-action@v1

      - name: Cache iOS SDK
        id: sdk-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.THEOS }}/sdks
          key: ios-sdk-15.0

      - name: Download iOS SDK
        if: steps.sdk-cache.outputs.cache-hit != 'true'
        run: |
          # Theos action sets $THEOS automatically
          git clone --quiet --depth=1 https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build Package
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS_DEVICE_IP: "" 
          ARCHS: "arm64 arm64e"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FilzaApplySandboxExt-Deb
          path: packages/*.deb
